[custom]

; ================= 1. 规则集定义 (按优先级从上到下) =================

; 直连、去广告与隐私防护 (最高优先级)
ruleset=🎯 全球直连,https://raw.githubusercontent.com/lexin2002/rules/refs/heads/main/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyListChina.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list

; 核心服务与特定平台
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=👨🏿‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list

; AI与游戏流媒体平台
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list

; 综合媒体与底层托底规则
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/lexin2002/rules/refs/heads/main/Yellow.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


; ================= 2. 策略组定义 =================

; [核心主干策略]
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 东亚故转`[]🔯 日本故转`[]🔯 美州故转`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🇺🇸 美州节点`[]🛩️ 普通节点`[]🕊️ 低速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

; [业务分流策略]
custom_proxy_group=📹 YouTube`select`[]🔯 东亚故转`[]🔯 日本故转`[]♻️ 自动选择`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🛩️ 普通节点`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT
custom_proxy_group=💬 Ai平台`select`[]🔯 日本故转`[]🔯 美州故转`[]🇺🇸 美州节点`[]🇯🇵 日本节点`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]🔯 日本故转`[]🔯 东亚故转`[]🔯 美州故转`[]🇯🇵 日本节点`[]🇭🇰 东亚节点`[]🇺🇸 美州节点`[]🛩️ 普通节点`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🔯 东亚故转`[]🔯 日本故转`[]🔯 美州故转`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🇺🇸 美州节点`[]🛩️ 普通节点`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🇺🇸 美州节点`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=🎵 TikTok`select`[]🔯 日本故转`[]🔯 美州故转`[]🇯🇵 日本节点`[]🇺🇸 美州节点`[]🛩️ 普通节点`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🔯 东亚故转`[]🔯 日本故转`[]🔯 美州故转`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🛩️ 普通节点`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=📲 Telegram`select`[]🔯 东亚故转`[]🔯 日本故转`[]🔯 美州故转`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]🔯 东亚故转`[]🔯 日本故转`[]🔯 美州故转`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🎮 游戏平台`select`[]🔯 东亚故转`[]🔯 日本故转`[]🔯 美州故转`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🛩️ 普通节点`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🔯 东亚故转`[]🔯 日本故转`[]🔯 美州故转`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🛩️ 普通节点`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=♻️ Speedtest`select`[]DIRECT`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🇺🇸 美州节点`[]🌐 其他地区
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 东亚节点`[]🇯🇵 日本节点`[]🐸 手动切换

; [地区与正则筛选策略 (强化排雷版)]
; 排除常见的机场提示信息（官网、重置、到期等）以防止报错
custom_proxy_group=🛩️ 普通节点`select`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|韩国|巴西|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|新加坡|台湾|TW|Taiwan|荷兰))^((?!(深港|游戏|剩余|流量|官网|到期|重置|群|地址|最新|0\.5|0\.1|0\.1倍|0\.1x|0\.5倍|0\.5x|2\.0|2倍|2x|3\.0|3倍|3x|4\.0|4倍|4x|5\.0|5倍|5x)).)*$
custom_proxy_group=🕊️ 低速节点`select`(?=.*(0\.5|0\.5倍|0\.5x|0\.1|0\.1倍|0\.1x))^((?!(官网|到期|重置|群|地址|最新)).)*$
custom_proxy_group=🇭🇰 东亚节点`select`(?=.*(香港|HK|Hong Kong|🇭🇰|韩|台湾|HongKong|新加坡|坡|狮城|SG|Singapore))^((?!(深港|US|游戏|剩余|流量|官网|到期|重置|群|地址|最新|2\.0|2倍|2x|3\.0|3倍|3x|4\.0|4倍|4x|0\.1|0\.1倍|0\.1x)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(游戏|剩余|流量|官网|到期|重置|群|地址|最新|2\.0|2倍|2x|3\.0|3倍|3x|4\.0|4倍|4x|0\.1|0\.1倍|0\.1x)).)*$
custom_proxy_group=🇺🇸 美州节点`select`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|巴西))^((?!(官网|到期|重置|群|地址|最新|0\.1x|0\.5x|限速)).)*$
custom_proxy_group=🌐 其他地区`select`(^(?!.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|新加坡|坡|狮城|SG|Singapore|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|巴西|剩余|官网|到期|重置|群|地址|最新)).*)
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media|流媒体)^((?!(官网|到期|重置|群|地址|最新)).)*$

; [故障转移 / 自动选择策略]
custom_proxy_group=🔯 东亚故转`fallback`(?=.*(香港|HK|Hong Kong|🇭🇰|韩|台湾|HongKong|新加坡|坡|狮城|SG|Singapore))^((?!(深港|游戏|剩余|流量|官网|到期|重置|0\.5|0\.5倍|0\.5x|2\.0|2倍|2x|3\.0|3倍|3x|4\.0|4倍|4x|5\.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🔯 日本故转`fallback`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(深港|游戏|剩余|流量|官网|到期|重置|0\.5|0\.5倍|0\.5x|2\.0|2倍|2x|3\.0|3倍|3x|4\.0|4倍|4x|5\.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🔯 美州故转`fallback`(?=.*(美|荷兰|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|巴西))^((?!(官网|到期|重置|0\.1x|0\.5x|限速)).)*$`http://www.gstatic.com/generate_204`300,50

; ================= 3. 其他设置 =================
enable_rule_generator=true
overwrite_original_rules=true
